This PR is to Setup project with essential libraries and configurations
atlp-rwanda/knights-ecomm-fe pull request #10
Opened 2024-06-06 08:29 UTC by maxCastro1

### Description
This PR sets up the project with essential libraries and configurations, ensuring a robust development environment and codebase structure. The following changes have been implemented:

**Library Installations:**

> Installed essential libraries: react-router-dom, axios, redux, react-redux, @reduxjs/toolkit, eslint, prettier, vite, vitest, @testing-library/react, @testing-library/jest-dom.
> ESLint Configuration:
> 
> Configured ESLint with recommended rules for TypeScript and React.
> Included plugins for react-hooks and prettier to enforce coding standards and best practices.
> Added rules to disable prop-types in favor of TypeScript type checking.

**Prettier Configuration:**

> Added Prettier configuration file for consistent code formatting.
> Integrated Prettier with ESLint to avoid conflicts and ensure cohesive code style enforcement.
> Script Updates:
> 
> Updated package.json scripts to include:
> dev for running Vite development server.
> build for compiling TypeScript and building the Vite project.
> lint for linting all JavaScript, JSX, TypeScript, and TSX files.
> format for formatting all files using Prettier.
> preview for running Vite preview server.

**SVG Import Handling:**

> 
> Installed and configured vite-plugin-svgr to handle SVG imports as React components.
> Created a TypeScript declaration file to handle .svg imports properly.
> Updated Vite configuration to include the svgr plugin.
> Path Aliases:
> 
> Set up path aliases in Vite configuration for cleaner and more manageable imports.

**Component Update:**

> Modified the Welcome component to use an SVG as a React component, demonstrating the new SVG import capability.
> Changes

**Libraries Installed:**

- react-router-dom
- axios
- redux
- react-redux
- @reduxjs/toolkit
- eslint
- prettier
- vite
- vitest
- @testing-library/react
- @testing-library/jest-dom

**Configurations Added:**

- .eslintrc.js
- .prettierrc
- vite.config.js

**Scripts Updated in package.json:**

Copy code
```
"scripts": {
  "dev": "vite",
  "build": "tsc && vite build",
  "lint": "eslint . --ext .js,.jsx,.ts,.tsx --report-unused-disable-directives --max-warnings 0",
  "format": "prettier --write .",
  "preview": "vite preview"
}
```
**SVG Handling:**

- Installed vite-plugin-svgr
- Created declaration.d.ts for SVG imports

2024-06-06 17:42 UTC, elijahladdie approved these changes

2024-06-06 17:51 UTC, faid-terence requested changes

2024-06-06 17:51 UTC, faid-terence commented on src/App.tsx
@maxCastro1 
Resolve these conflicts !!

2024-06-06 17:51 UTC, faid-terence commented on src/redux/actions/productAction.ts
@maxCastro1 
Please keep the URL as an environment variable we shouldnot push it on github

2024-06-07 07:13 UTC, faid-terence approved these changes
Nice Work @maxCastro1 !

2024-06-07 07:14 UTC, merged