feat-OTP-2FA
atlp-rwanda/knights-ecomm-fe pull request #30
Opened 2024-06-21 11:59 UTC by Calebgisa72

What does this PR do?
This PR adds and refines the OTP (One-Time Password) verification functionality for enhanced user account security during login and registration.

Description of Task to be completed
UI Implementation:

- Designed and implemented the OTP verification page with a responsive layout.
- Added input fields for users to enter the 6-digit OTP.

State Management:

- Integrated OTP input handling using React state.
- Managed OTP state updates and error handling with custom logic.

API Integration:

- Connected the OTP verification page to the backend API for OTP submission and validation.
- Added error handling to display appropriate messages for invalid or expired OTPs.
- Implemented functionality for resending OTPs and handling the API response.

Error Handling:

- Displayed user-friendly error messages for incorrect OTP or server-related issues.
- Used react-hot-toast for toast notifications to inform users about OTP status and errors.

Testing:

- Added unit tests for OTP input handling and state updates.
- Ensured the OTP component behaves correctly under various scenarios, including valid, invalid, and empty inputs.

2024-06-21 17:54 UTC, faid-terence commented
@Calebgisa72 
Too many commit messages !

2024-06-23 15:54 UTC, aimedivin approved these changes

2024-06-23 17:03 UTC, Ndevu12 approved these changes

2024-06-23 17:25 UTC, MC-Knight approved these changes

2024-06-23 21:44 UTC, elijahladdie requested changes

2024-06-23 21:44 UTC, elijahladdie commented on src/images/iconoir_xmark-circle (2).svg
Can you move this image in assets folder please

2024-06-23 21:44 UTC, elijahladdie commented on src/pages/Authentication/GoogleLoginSuccess.tsx
> +        console.log(response.data);
remove this console

2024-06-23 23:01 UTC, GSinseswa721 approved these changes

2024-06-24 08:04 UTC, faid-terence approved these changes
Approved @Calebgisa72 !

2024-06-24 08:05 UTC, merged