Feature addition of new product by the vendor
atlp-rwanda/knights-ecomm-fe pull request #35
Opened 2024-06-24 17:42 UTC by maxCastro1

### **Overview**
This pull request introduces the ability for vendors to create new products within the dashboard. The implementation includes form fields for essential product details, image upload functionality with multiple image previews, and validation enhancements.

**Changes**
Form Fields for Product Details:

> Product Name: Input field for the name of the product.
> Description: Textarea for providing a detailed description of the product.
> Category: Two input fields for specifying product categories and a dropdown for selecting predefined categories.
> Quantity: Input field for specifying the available quantity of the product.
> Pricing: Input field for setting the price of the product in Rwf.

Image Upload Functionality:

> Implemented an image upload input allowing vendors to select multiple images.
> Displayed previews for all selected images to provide immediate visual feedback.
> Utilized state management to handle and store selected images and their previews.

State Management:

> 
> Introduced state variables for managing form inputs and image data using React's useState hook.
> Ensured type safety by correctly typing state variables and event handlers with TypeScript.

Form Submission:

> Added a submit button that logs the form data for now, demonstrating the collection of all input values, including images.

Styling Enhancements:

> 
> Applied Taiwind to ensure a user-friendly and visually appealing form layout.
>  Detailed Implementation

Product Details Form:

> 
> Each input field is linked to its respective state variable, updating the state on user input.
> The selectedOption state variable is used to manage the dropdown selection for predefined categories.

Image Upload and Preview:

> The handleImageUpload function handles the file input change event, reading multiple files and generating preview URLs.
> Updated the state to store multiple images and their previews by appending new files to the existing state.

State Management:

> 
> Used useState for each form field and image-related state, ensuring clear and manageable state updates.
> Typed event handlers with ChangeEvent to ensure TypeScript correctly infers the types of events and state variables.
> Benefits

**Testing and Validation**

> Verified that all form inputs correctly update their respective state variables.
> Ensured that multiple images can be selected and displayed as previews.
> Confirmed that form submission logs all entered data accurately.

Next Steps

- Validation: Implement form validation to ensure all required fields are filled out correctly.
- Image Handling: Add functionality to remove individual images from the preview list before form submission.
- Enhanced Features: Consider integrating third-party libraries for advanced image handling features, such as cropping and resizing.

Screenshots (to be added)

2024-06-24 21:33 UTC, MC-Knight approved these changes

2024-06-25 05:59 UTC, aimedivin requested changes
@maxCastro1 , you can also work on the mobile responsiveness, elements are not well aligned.

2024-06-25 07:32 UTC, GSinseswa721 approved these changes

2024-06-25 10:13 UTC, Ndevu12 approved these changes

2024-06-25 12:37 UTC, faid-terence approved these changes
PR Approved @maxCastro1 !

2024-06-25 12:38 UTC, merged