Enable to delete a product
atlp-rwanda/knights-ecomm-fe pull request #36
Opened 2024-06-25 15:03 UTC by UwicyezaG

### Description

The seller should be able to delete a specific item in their collection such that they can remove items they no longer deal in or were erroneously added. This functionality ensures that sellers can manage their product listings effectively and maintain an accurate inventory.

### Definition of Done:

- Sellers can see and use the delete option for each item in their inventory.
- Deletion requires seller confirmation to proceed.
- Successfully deleted items display a confirmation message.
- Canceled deletions do not alter the inventory.
- Errors, such as attempting to delete a non-existent item or encountering deletion failures, are appropriately managed and communicated to the seller.

2024-06-27 16:02 UTC, MC-Knight approved these changes

2024-06-30 19:24 UTC, faid-terence approved these changes
@UwicyezaG 
Please rebase with develop and resolve the conflicts 
And increase the test coverage !!

2024-06-30 19:25 UTC, faid-terence requested changes
@UwicyezaG
Please rebase with develop and resolve the conflicts
And increase the test coverage !!

2024-07-04 08:42 UTC, maxCastro1 approved these changes

2024-07-04 09:30 UTC, Ndevu12 approved these changes

2024-07-04 20:48 UTC, aimedivin requested changes

2024-07-04 20:48 UTC, aimedivin commented on src/Routes/Router.tsx
> +  const isAdmin = decodedToken?.userType.toLowerCase() === 'admin';
@UwicyezaG  You must use the value from 'role' instead of 'userType', as the token does not contain userType.

2024-07-05 06:28 UTC, faid-terence requested changes

2024-07-05 06:28 UTC, faid-terence commented on src/components/Products/DashboardSingleProduct/DashboardSingleProduct.tsx
@UwicyezaG Are we using userType or role ?

2024-07-05 06:29 UTC, faid-terence commented
@UwicyezaG 
Work on the change requests and rebase with develop to resolve the conflicts

2024-07-05 14:07 UTC, GSinseswa721 approved these changes

2024-07-06 00:03 UTC, elijahladdie approved these changes

2024-07-06 06:44 UTC, faid-terence approved these changes
PR Approved @UwicyezaG !

2024-07-06 06:44 UTC, merged