feat-wishlist-management
atlp-rwanda/knights-ecomm-fe pull request #53
Opened 2024-07-04 18:12 UTC by Calebgisa72

What does this PR do?

- This PR enhances the buyer experience by implementing comprehensive management features for the wishlist functionality.

Description of Task Completed

Tasks completed in this PR:

- Designed and integrated UI components for managing the Buyer wishlist.
- Implemented state management using Redux to maintain wishlist state across sessions.
- Added functionality to display wishlist icons on products when users are logged in, enhancing user interaction.
- Ensured seamless integration with backend APIs for wishlist operations, including adding, removing, and updating wishlist items.
- Conducted unit tests to verify functionality and maintain code quality, ensuring robust performance under various scenarios.

How should this be manually tested?

- Ensure You have backend service running and set VITE_APP_API_URL in your .env file.
- Clone this repository and navigate to the project director

`git clone -b ft-register https://github.com/atlp-rwanda/knights-ecomm-fe.git
cd knights-ecomm-fe
git checkout ft-landing-page
npm i
npm run dev`

2024-07-05 06:47 UTC, faid-terence commented
@Calebgisa72 Rebase with develop to resolve the conflicts and increase the coverage as well !

2024-07-05 12:37 UTC, aimedivin approved these changes
@Calebgisa72 Please remove console logs

2024-07-06 06:46 UTC, faid-terence commented
Hey @Calebgisa72 
Please rebase with develop and resolve the conflicts !

2024-07-06 06:51 UTC, faid-terence requested changes
@Calebgisa72 
Work on these feedbacks and re-request for reviews from me  after they are applied !

2024-07-06 06:51 UTC, faid-terence commented on src/pages/WishlistPage/WishlistPage.tsx
@Calebgisa72 
Instead of `console.error('Failed to fetch wishlist', error)` 
Can we use toast.error and display the error to the user 
To enhnace a good user experience !

2024-07-06 06:51 UTC, faid-terence commented on src/utils/wishlistFunctions/addProduct.ts
@Calebgisa72 
Please avoid using any for Dispatch 
You can use AppDispatch()

2024-07-06 06:53 UTC, GSinseswa721 approved these changes

2024-07-06 08:43 UTC, maxCastro1 approved these changes

2024-07-06 09:39 UTC, faid-terence approved these changes
Good Job @Calebgisa72 
PR Approved !

2024-07-06 09:40 UTC, merged