Implement In-App-Notificatons
atlp-rwanda/knights-ecomm-fe pull request #72
Opened 2024-07-20 10:09 UTC by Calebgisa72

What does this PR do?

- This PR introduces new features to the in-app notifications system, including real-time notifications using WebSockets, marking selected notifications as read, and clearing selected notifications.

Description of Task Completed

- Designed and integrated UI components for the in-app notifications
- Implemented real-time notifications using WebSockets
- Added functionality to mark selected notifications as read
- Added functionality to clear selected notifications
- Ensured seamless integration with backend services for notification operations
- Conducted unit tests to verify functionality and maintain code quality

How should this be manually tested?

- Ensure You have backend service running and set VITE_APP_API_URL in your .env file.
- Clone this repository and navigate to the project director

2024-07-21 12:59 UTC, MC-Knight approved these changes

2024-07-21 18:26 UTC, faid-terence requested changes

2024-07-21 18:26 UTC, faid-terence commented on src/__test__/dashbord/dashboardAccount.test.tsx
@Calebgisa72 @Ndevu12 
This should be Dashboard Account test not Dashboard Account tes

2024-07-21 19:28 UTC, Calebgisa72 commented on src/__test__/dashbord/dashboardAccount.test.tsx
Solved!!

2024-07-21 21:30 UTC, aimedivin approved these changes

2024-07-22 07:17 UTC, faid-terence approved these changes
Nice Work @Calebgisa72 and @Ndevu12 
PR Approved !

2024-07-22 07:17 UTC, merged