Ft order management
atlp-rwanda/knights-ecomm-fe pull request #73
Opened 2024-07-20 19:41 UTC by aimedivin

#### What does this PR do?

#### Description of Task to be completed?

#### How should this be manually tested?

#### What are the relevant pivotal tracker/Trello stories?

#### Screenshots (if appropriate)

2024-07-22 07:18 UTC, faid-terence commented
@aimedivin , @GSinseswa721 
What;s the progress on this PR?

2024-07-23 06:51 UTC, aimedivin commented
> @aimedivin , @GSinseswa721 What;s the progress on this PR?

@faid-terence  PR is now ready for review

2024-07-23 08:36 UTC, Ndevu12 approved these changes

2024-07-23 08:55 UTC, maxCastro1 approved these changes

2024-07-23 09:25 UTC, faid-terence requested changes

2024-07-23 09:25 UTC, faid-terence commented on src/__test__/utils/formartDate&Time.test.ts
@aimedivin 
Remove the console.log

2024-07-23 10:00 UTC, elijahladdie commented on src/pages/Orders/SingleAdminOrder.tsx
> +      if ((error as AxiosError).response && [400, 404].includes((error as AxiosError).response!.status)) {
remove the console please

2024-07-23 10:01 UTC, elijahladdie approved these changes

2024-07-23 10:46 UTC, MC-Knight approved these changes

2024-07-23 10:54 UTC, faid-terence approved these changes
Nice Work @GSinseswa721 and @aimedivin 
PR Approved !

2024-07-23 10:55 UTC, merged