feature Implement Transactions View for Admin to Display All Payments
atlp-rwanda/knights-ecomm-fe pull request #76
Opened 2024-07-23 17:29 UTC by maxCastro1

### Description
This PR introduces a new Transactions component that allows admins to view all payment transactions. The implementation includes fetching transaction data from the backend and displaying it in a user-friendly interface with detailed statistics and a list of transactions.

### Changes Implemented

**Transactions Component**

- Added a new Transactions component that fetches payment data from the backend API.
- Displayed key statistics including total amount, total transactions, average payment amount, and captured amount.
- Provided a table listing individual transactions with details such as payment ID, amount, date, status, and payment method.

**API Integration**

- Implemented a useEffect hook to fetch payment data from the backend when the component mounts.
- Utilized Axios for making API requests with proper authorization headers.

**Error Handling**

- Added error handling to display appropriate messages if the data fetch fails.
- Included loading states to indicate data fetching progress.

**Styling and Layout**

- Applied CSS styles to ensure a clean and responsive design.
- Used Flexbox and Grid for layout management.
- Incorporated PropagateLoader for displaying a loading spinner during data fetch.

2024-07-23 19:18 UTC, faid-terence approved these changes
PR Approved @maxCastro1 !

2024-07-23 19:19 UTC, faid-terence commented
@maxCastro1 
Rebase with develop to resolve errors in Router.tsx

2024-07-23 20:08 UTC, MC-Knight approved these changes

2024-07-23 20:09 UTC, faid-terence requested changes
@maxCastro1 
No work in this PR

2024-07-24 13:02 UTC, UwicyezaG approved these changes

2024-07-24 13:57 UTC, GSinseswa721 approved these changes

2024-07-24 15:55 UTC, Ndevu12 approved these changes

2024-07-24 20:48 UTC, closed without merging